import { GetServerSideProps } from "next";
import React from "react";
import { ParsedUrlQuery } from "querystring";
import Layout from "../../components/layout";

interface Props {
  search?: string;
}

export default class Items extends React.Component<Props> {
  render() {
    console.log("props", this.props);
    return (
      <Layout searchQuery={this.props.search}>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
        <h1>Items Component</h1>
      </Layout>
    );
  }
}

interface IParams extends ParsedUrlQuery {
  search?: string;
}

export const getServerSideProps: GetServerSideProps<IParams> = async ({
  query,
}) => {
  return {
    props: query,
  };
};
